name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6 # or alternative dependency management
      - name: Run tests
        uses: php-actions/phpunit@v3
        with:
          version: "9.5"
          php_version: "8.1.0"
          php_extensions: GD xdebug
          coverage_cobertura: "./coverage/coverage.xml"
        env:
          XDEBUG_MODE: "coverage"

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage/coverage.xml
      - name: Adding markdown
        run: | 
            echo "## Coverage" >> README.md
            echo "![coverage](./coverage/coverage.xml)" >> README.md

    # ... then your own project steps ...